valor = input("Introduce una cadena: ")
print("Cadena:", valor)
print("Longitud:", len(valor))
print("Alfanumérico:", valor.isalnum())
print("Alfabético:", valor.isalpha())
print("Decimal:", valor.isdecimal())
print("Dígito:", valor.isdigit())
print("Identificador:", valor.isidentifier())
print("Mayúsculas:", valor.upper())
print("Minúsculas:", valor.lower())
print("Capital:", valor.capitalize())
print("Título:", valor.title())
print("Invierta Mayúsculas-Minúsculas:", valor.swapcase())
print("Reemplaza 'o' por 'u':", valor.replace("o", "u"))
print("Reemplaza 'o' por 'u' (1 vez):", valor.replace("o", "u", 1))
print("Cuenta 'o':", valor.count("o"))
print(valor.startswith("A"))
print(valor.endswith("n"))
