Valor=input("Dame una cadena: ")
print("El valor en cadena es:", str(Valor))
Valor=input("Dame un Entero: ")
print("El valor en entero es:", int(Valor))
Valor=input("Dame un Flotante: ")
print("El valor en flotante es:", float(Valor))
Valor=input("Dame un Booleano: ")
print("El valor en booleano es:", bool(Valor))
